# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4986ca56454d477cdd622ec3636799ebe853089ada43e7711b8f477e7522ff4ad5a7c8e6bf3e093e03507bce54a8e770ba58bb37a7936f1d2dc1f364a565788d

test:
  secret_key_base: a3511c4407c52ccf8e5620daa4ad1e65cb1ec016a915a986fb3bab39797f9405fadee9836d561400d07d52aa5778278addd2795dfde8fdaf2985ebb3de310429

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
